name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn run test
  build:
    name: 'Build'
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [ 1.35.2 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Convert Deno Module to NPM
        run: deno run --allow-env --allow-read --allow-write --allow-run scripts/npm.ts ${{ github.ref_name }}

      - name: Install modules
        run: |
          cd npm
          yarn

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
