name: Tests
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [ 1.35.2 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Deno fmt
        run: deno task fmt:check
      - name: Build Deno Module
        run: deno task build
      - name: Test Deno Module
        run: deno task test
      - name: Create coverage report
        run: deno task coverage
