name: Tests
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn run test
      - name: Build
        run: yarn run build
      - name: Build CJS
        run: yarn run build:cjs
